# Generated by Django 4.2.2 on 2023-07-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nas_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
