# Generated by Django 4.2.2 on 2023-07-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_nas_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nas_sizes',
            new_name='has_sizes',
        ),
    ]
